### ISSUE TITLE
Loss become a NaN using tensorflow-rocm (gfx803)

### ISSUE THREAD

**Issue by aruno14** [ROCmSoftwarePlatform/rocSPARSE#215]
### What is the expected behavior
Fitting on GPU must give a coherent result, similar to the result on CPU.

### What actually happens
Loss value become a NaN during fitting and after that an `InvalidArgumentError` is raised.

```
Epoch 56/150
 1/10 [==>...........................] - ETA: 0s - loss: 0.1562 - mse: nanTraceback (most recent call last):
File "testGPU.py", line 19, in <module>
    model.fit(X, Y, batch_size=batch_size, epochs=epochs)
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/home/arnaud/.local/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Input to reshape is a tensor with 12 values, but the requested shape has 1175549453906477056
	 [[node gradient_tape/mean_squared_error/Reshape (defined at testGPU.py:19) ]] [Op:__inference_train_function_508]
```

### How to reproduce
Below code, work on CPU but failed on GPU.
```
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense

X = tf.fill((300, 5), 5)
Y = tf.fill((300, 5), 10)

model = tf.keras.Sequential()
model.add(Dense(5))
model.compile(optimizer='adam', loss='mse', metrics=['mse'])

epochs = 150
batch_size = 32

print("Fitt...")
#with tf.device('/CPU:0'):#To test on GPU
model.fit(X, Y, batch_size=batch_size, epochs=epochs)

print("Evaluate...")
model.evaluate(X, Y)

print("Predict...")
result = model.predict(tf.fill((1, 5), 5))
print(result)
```

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx803  (Fiji [Radeon R9 FURY / NANO Series]) |
| CPU | AMD Ryzen 5 3500X 6-Core Processor |

I am sorry, I don't know how to check versions, but all should be the latest. I installed ROCm 3.9.1.
| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

I installed ROCm like explained on below page on Ubuntu 20.04.1:
https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html

Then, I installed I followed below page:
https://github.com/xuhuisheng/rocm-build/blob/develop/docs/gfx803.md

**Comment by xuhuisheng** [comment]
@aruno14 
Could be dumplicated by https://github.com/RadeonOpenCompute/ROCm/issues/1265

**Comment by aruno14** [comment]
@xuhuisheng 
Thank you for your fast reply.
Oh, Yes, It seems to be the same problem.
But, I got the same problem with ROCm-3.5.1 (maybe I made something wrong). :(

**Comment by xuhuisheng** [comment]
Test on ROCm-3.5.1, gfx803(RX580), Tensorflow-2.3.2, ubuntu-20.04.1.
Donot meet NaN.

```
2020-11-22 15:54:59.332371: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libamdhip64.so
2020-11-22 15:55:00.015085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: Device 67df     ROCm AMD GPU ISA: gfx803
coreClock: 1.34GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 0B/s
2020-11-22 15:55:00.229435: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
2020-11-22 15:55:00.230769: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libMIOpen.so
2020-11-22 15:55:00.492533: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocfft.so
2020-11-22 15:55:00.493953: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocrand.so
2020-11-22 15:55:00.494038: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-11-22 15:55:00.494440: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-22 15:55:00.519206: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2394255000 Hz
2020-11-22 15:55:00.520310: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3e55bf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-22 15:55:00.520340: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-22 15:55:00.522361: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f5a78d4c160 initialized for platform ROCM (this does not guarantee that XLA will be used). Devices:
2020-11-22 15:55:00.522396: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Device 67df, AMDGPU ISA version: gfx803
2020-11-22 15:55:00.522510: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 0 with properties: 
pciBusID: 0000:02:00.0 name: Device 67df     ROCm AMD GPU ISA: gfx803
coreClock: 1.34GHz coreCount: 36 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 0B/s
2020-11-22 15:55:00.522558: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
2020-11-22 15:55:00.522583: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libMIOpen.so
2020-11-22 15:55:00.522606: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocfft.so
2020-11-22 15:55:00.522628: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocrand.so
2020-11-22 15:55:00.522689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-11-22 15:55:00.522720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-22 15:55:00.522734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-11-22 15:55:00.522746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-11-22 15:55:00.522853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7399 MB memory) -> physical GPU (device: 0, name: Device 67df, pci bus id: 0000:02:00.0)
Fitt...
2020-11-22 15:55:01.167596: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:01.172223: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:01.175758: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
Epoch 1/150
2020-11-22 15:55:01.527674: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:01.533106: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
Epoch 150/150
10/10 [==============================] - 0s 2ms/step - loss: 0.0041 - mse: 0.0041
Evaluate...
2020-11-22 15:55:05.634020: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:05.638974: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:05.642821: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:05.737168: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
10/10 [==============================] - 0s 2ms/step - loss: 0.0038 - mse: 0.0038
Predict...
2020-11-22 15:55:05.782896: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:05.787163: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:05.790019: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-11-22 15:55:05.832422: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
[[ 9.861336  9.999986  9.999457 10.000001  9.999965]]

```

**Comment by aruno14** [comment]
Thank you to test it!
I installed version 3.5.1 again, and I got correct result too.
But I still have a problem with another model (https://github.com/aruno14/genderRecognition)
During fitting accuracy improve, but there is no increase in evaluation (evaluation loss improve during fitting).

```
148/148 [==============================] - 200s 1s/step - accuracy: 0.6441 - loss: 0.6173 - val_accuracy: 0.4924 - val_loss: 0.7569
...
148/148 [==============================] - 200s 1s/step - accuracy: 0.7631 - loss: 0.4713 - val_accuracy: 0.4799 - val_loss: 2.2815
```

**Comment by aruno14** [comment]
@xuhuisheng
> I suggest reopen issue for rocBLAS, not rocSPARSE.

I will do that. Thank you.
